version: "3"
services:
 app:
   container_name: app
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - 8000:8000


 nginx:
   container_name: nginx
#   ports:
#     - 8000:8000
   image: nginx
   volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
     - ./staticfiles/:/var/html/static/
#   command: [nginx-debug, '-g', 'daemon off;']
   links:
     - app
